### ISSUE TITLE
Feature Request - Add an option to automatically mark attendance

### ISSUE THREAD

**Issue by killbotXD** [devlup-labs/meet-scheduler#50]
Many Courses have attendance form shared in the chat which are google forms.
A feature can be added to check if a link has been posted in the chat and then making a post request with the persons name and roll number.

**Comment by anshulahuja98** [comment]
I don't believe this can be done abstractly. Just randomly making a request won't work. And I don't believe we can expect the user to setup the form system if we provide some tools for this.

**Comment by anshulahuja98** [comment]
We can change the scope to perhaps sound an alarm when a regex match is found in chat. That can be the scope

**Comment by killbotXD** [comment]
cant we just trigger a post request when there is a regex match?

**Comment by hirenchalodiya1** [comment]
I think that requires an OAuth token, for that we need a login mechanism or something

**Comment by killbotXD** [comment]
> I think that requires an OAuth token, for that we need a login mechanism or something

Yeah I remember @harsh-not-haarsh trying to make a script to post the attendance, he stopped at the same Issue

**Comment by harsh-not-haarsh** [comment]
The problem with this is: Google forms don't have an API to fill in forms, so I thought of making a POST request to the form (after scraping the field ID of each field in the form) but still we need to pass user credentials and since that is not secure, An automatic tool would require to open the link in the browser where I am already logged in.

I was thinking of making a slack channel, where one person can send the link and attendance is marked for everyone present in the channel.

**Comment by anshulahuja98** [comment]
Let's take this discussion offline.

Closing this issue for now.
